/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Condition#getTeam <em>Team</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Condition#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Condition#getGoal <em>Goal</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Condition#getComparator <em>Comparator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.Condition#getDistance <em>Distance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Team</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Team</em>' reference.
   * @see #setTeam(TeamDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition_Team()
   * @model
   * @generated
   */
  TeamDefinition getTeam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Condition#getTeam <em>Team</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Team</em>' reference.
   * @see #getTeam()
   * @generated
   */
  void setTeam(TeamDefinition value);

  /**
   * Returns the value of the '<em><b>Robot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' reference.
   * @see #setRobot(RobotDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition_Robot()
   * @model
   * @generated
   */
  RobotDefinition getRobot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Condition#getRobot <em>Robot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot</em>' reference.
   * @see #getRobot()
   * @generated
   */
  void setRobot(RobotDefinition value);

  /**
   * Returns the value of the '<em><b>Goal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' reference.
   * @see #setGoal(GoalDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition_Goal()
   * @model
   * @generated
   */
  GoalDefinition getGoal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Condition#getGoal <em>Goal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' reference.
   * @see #getGoal()
   * @generated
   */
  void setGoal(GoalDefinition value);

  /**
   * Returns the value of the '<em><b>Comparator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparator</em>' attribute.
   * @see #setComparator(String)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition_Comparator()
   * @model
   * @generated
   */
  String getComparator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Condition#getComparator <em>Comparator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparator</em>' attribute.
   * @see #getComparator()
   * @generated
   */
  void setComparator(String value);

  /**
   * Returns the value of the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance</em>' attribute.
   * @see #setDistance(int)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getCondition_Distance()
   * @model
   * @generated
   */
  int getDistance();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.Condition#getDistance <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance</em>' attribute.
   * @see #getDistance()
   * @generated
   */
  void setDistance(int value);

} // Condition
