/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.RunStatement#getFunction <em>Function</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getRunStatement()
 * @model
 * @generated
 */
public interface RunStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' reference.
   * @see #setFunction(TaskDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getRunStatement_Function()
   * @model
   * @generated
   */
  TaskDefinition getFunction();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.RunStatement#getFunction <em>Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(TaskDefinition value);

} // RunStatement
