/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl4.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getTeam <em>Team</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getRobot <em>Robot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getTaskStatement()
 * @model
 * @generated
 */
public interface TaskStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Team</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Team</em>' reference.
   * @see #setTeam(TeamDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getTaskStatement_Team()
   * @model
   * @generated
   */
  TeamDefinition getTeam();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getTeam <em>Team</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Team</em>' reference.
   * @see #getTeam()
   * @generated
   */
  void setTeam(TeamDefinition value);

  /**
   * Returns the value of the '<em><b>Robot</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robot</em>' reference.
   * @see #setRobot(RobotDefinition)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getTaskStatement_Robot()
   * @model
   * @generated
   */
  RobotDefinition getRobot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getRobot <em>Robot</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Robot</em>' reference.
   * @see #getRobot()
   * @generated
   */
  void setRobot(RobotDefinition value);

  /**
   * Returns the value of the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' containment reference.
   * @see #setStatement(MoveToStatement)
   * @see org.xtext.example.mydsl4.myDsl.MyDslPackage#getTaskStatement_Statement()
   * @model containment="true"
   * @generated
   */
  MoveToStatement getStatement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl4.myDsl.TaskStatement#getStatement <em>Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' containment reference.
   * @see #getStatement()
   * @generated
   */
  void setStatement(MoveToStatement value);

} // TaskStatement
