/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl4;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
